"""
====================================================
Merge images
====================================================

In this example, we use the Chelsea cat image to demonstrate how the ``merge_images``
function works. The image will be shifted slightly to demonstrate how this works.
"""

import matplotlib.pyplot as plt
import skimage
from scipy import ndimage
from skimage.data import chelsea

import oic_toolkit

# Import the Chelsea image as the example
target_img = skimage.color.rgb2gray(chelsea())
h, w = target_img.shape

# Shift the image
true_shift = (-18.5, 25.2)

# Create the moved image
moving_img = ndimage.shift(target_img, shift=(-true_shift[0], -true_shift[1]), cval=0.0)

# Display the two images to show the translational shift
merged = oic_toolkit.display.merge_images(target_img, moving_img)

fig, ax = plt.subplots(figsize=(5, 5))
ax.imshow(merged)
ax.axis("off")
plt.tight_layout()
plt.show()

###############################################################################
# Merging an image with colored labels
# ------------------------------------
#
# A common task is to display the output of a segmentation algorithm by labeling the
# cell labels in color. This example shows how to use the ``merge_images()`` function to
# combine the image and the resulting labels generated by ``scikit-image``'s
# ``label2rgb`` function.

# First load an example image
image = skimage.data.human_mitosis()

# Segment the image
thresholds = skimage.filters.threshold_otsu(image)
mask = image > thresholds

mask = skimage.morphology.remove_small_holes(mask, max_size=100)

# Add watershedding
labels = oic_toolkit.segment.separate_objects(
    mask, h_value=None, min_distance=5, threshold_abs=1
)

# Use label2rgb to convert the labels into color
rgb_labels = skimage.color.label2rgb(labels, bg_label=0, image=image)

merged = oic_toolkit.display.merge_images(image, rgb_labels, mode="blend")

fig, ax = plt.subplots(figsize=(5, 5))
ax.axis("off")
plt.tight_layout()
plt.imshow(merged)
plt.show()
