name: Publish to PyPI

on:
  release:
    types: [published]  # Triggers whenever a GitHub Release is created

jobs:
  pypi-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write

    environment: pypi

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv-action@v5
        with:
          version: "latest"

      - name: Build distribution files
        run: uv build

      - name: Publish package to PyPI
        run: uv publish